version: "3.9"

services:
  devpod:
    image: vsc-universal
    container_name: devpod

    restart: unless-stopped
    ports:
      - "${SSHD_PORT:-2222}:22"

    working_dir: /workspace

    environment:
      TZ: ${TIMEZONE:-Asia/Shanghai}
      START_SSHD: "true"
      SSHD_PORT: "22"
      USERNAME: ${SSH_USERNAME:-codespace}
      NEW_PASSWORD: ${SSH_PASSWORD:?SSH_PASSWORD must be set in .env file}
      GATEWAY_PORTS: ${GATEWAY_PORTS:-yes}

    volumes:
      - ./workspace:/workspace
      - vsc-home:/home/dev
      - /var/run/docker.sock:/var/run/docker.sock

    tty: true
    stdin_open: true
    privileged: true
    command: /bin/sh -c "echo \"${SSH_USERNAME}:${SSH_PASSWORD}\" | chpasswd && /usr/local/share/ssh-init.sh && /usr/local/bin/configure-agent-runtime && tail -f /dev/null"

volumes:
  vsc-home: